### ISSUE TITLE
archive?

### ISSUE THREAD

**Issue by ghost** [Anonyymi/miniboard#26]
Was wondering, do you plan to implement archive of any type? One thing that separates boards is archive functions. Why? Because someone can just post like 100 times to destroy an entire board if the board is set to delete the 100th post. The archive feature prevents people from trying to clear the entire board by posting 100 times.

**Comment by denamuumi** [comment]
In other words: eg. TinyIB has maximum amount of threads per board and when new thread is posted the least active thread is deleted?

Simple but suboptimal solution. A more sophisticated criteria for clearing inactive threads would be more than welcome I think.

First solution to combat this vulnerability would be to not delete threads when max amount exceeds so that they are visible again after the spam threads are deleted.

**Comment by Anonyymi** [comment]
We can just mark threads deleted instead of actually deleting them. Then a scheduled background job could delete them daily.
